# Generated by Django 3.2.6 on 2021-09-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210830_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='canApproveInventory',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='canDistributeInventory',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
