# Generated by Django 3.2.6 on 2021-10-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_canapproveleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='canManageAsset',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
