# Generated by Django 4.0.4 on 2022-06-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_canmanageasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone1',
            field=models.PositiveBigIntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone2',
            field=models.PositiveBigIntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Officer'), (1, 'Pion'), (2, 'Typist'), (3, 'Driver'), (4, 'Consultant'), (20, 'Others')], default=0),
        ),
    ]
