# Generated by Django 4.0.4 on 2022-06-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_image_profile_phone1_profile_phone2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone1',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone2',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True),
        ),
    ]
