# Generated by Django 4.0.4 on 2022-06-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_phone1_alter_profile_phone2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='canManageDriver',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
