# Generated by Django 4.0.4 on 2022-12-27 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_canmanagedriver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='canManageDriver',
        ),
    ]
