# Generated by Django 3.2.6 on 2021-09-08 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_alter_inventory_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='distributed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='distributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
