# Generated by Django 3.2.6 on 2021-09-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210908_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
