# Generated by Django 3.2.6 on 2021-09-14 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210914_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='lastModifiedDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='approveDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='distributionDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='requestDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
