# Generated by Django 3.2.6 on 2021-09-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approveDate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
