# Generated by Django 3.1.2 on 2022-01-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_alter_leave_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
