# Generated by Django 3.2.6 on 2021-10-06 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0003_assethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='next_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_assets', to=settings.AUTH_USER_MODEL),
        ),
    ]
