# Generated by Django 3.2.6 on 2021-10-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20211006_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='approved',
        ),
    ]
