# Generated by Django 4.0.4 on 2022-06-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_alter_asset_id_alter_assethistory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Others'), (1, 'Desktop'), (2, 'Laptop'), (3, 'Printer'), (50, 'Car')], default=0),
        ),
    ]
